services:
  ai-video-editor:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "7860"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_HOST=host.docker.internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.ai-video-editor.rule=Host(`ai-video-editor.sebastianmorales.sbs`)
      - 'traefik.http.routers.ai-video-editor.entryPoints=http,https'
      - traefik.http.routers.ai-video-editor.tls=true
      - traefik.http.services.ai-video-editor.loadbalancer.server.port=7860
    restart: unless-stopped
